title: htp
author: John Kitchin
copyright: "2026"
logo: ""

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/jkitchin/htp-2026
  branch: main
  path_to_book: docs

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

sphinx:
  config:
    html_theme_options:
      use_download_button: true
